# Generated by Django 4.0.4 on 2022-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_menu_alter_userprofile_email_userprofile_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=64),
        ),
    ]
