# Generated by Django 4.0.4 on 2022-05-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_articlemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='Article',
        ),
    ]
