# Generated by Django 4.0.4 on 2022-05-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_article_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='article_type',
        ),
    ]
